MONGODB_HOST: mongodb.phemanth.in
REDIS_HOST: redis.phemanth.in
CATALOGUE_HOST: catalogue.phemanth.in
CART_HOST: cart.phemanth.in
USER_HOST: user.phemanth.in
RABBITMQ_HOST: rabbitmq.phemanth.in
MYSQL_HOST: mysql.phemanth.in
SHIPPING_HOST: shipping.phemanth.in
PAYMENT_HOST: payment.phemanth.in
